### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by Thaerious** [cwrc/NERVE#81]
While loading schemas from an ssl source the server throws a SSLHandshakeException.

at ca.sharcnet.dh.scriber.encoder.EncoderBase.schema(EncoderBase.java:87)
at ca.sharcnet.dh.nerve.Scriber.createManager(Scriber.java:96)
at ca.sharcnet.dh.nerve.Scriber.dictionary(Scriber.java:162)

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by jefferya** [comment]
Could be the following:

- version of Java / openJDK before a certain version of 1.8 did not support LetEncrypt
- import the LetEncrypt public cert into the truststore -- something like
  -  `keytool -import -trustcacerts -alias root -file /etc/letsencrypt/live/prod-01.cwrc.ca/chain.pem  -keystore  truststore`
  - <https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html>

**Comment by Thaerious** [comment]
Switching to Tomcat remedied the issue.
